import os
import shutil
import hashlib
import json
import datetime
import subprocess
from pathlib import Path
from prolog.hasher import hash_path
from prolog.utils.jsondb import load_inventory, save_inventory
from prolog.idea_forge import random_idea

BASE_DIR = Path.home() / "Projects"
DB_PATH = BASE_DIR / ".prolog" / "projects.json"
CATEGORIES = [
    "idea",
    "started",
    "in_progress",
    "working",
    "finished",
    "broken"
]


def ensure_environment():
    os.makedirs(BASE_DIR / ".prolog", exist_ok=True)
    if not DB_PATH.exists():
        with open(DB_PATH, "w") as f:
            json.dump({"projects": []}, f, indent=4)


def generate_id(hash_str: str) -> str:
    return f"PRJ-{hash_str[:6].upper()}"


def classify(path, category):
    ensure_environment()
    if category not in CATEGORIES:
        print(f"[!] Invalid category. Using 'in_progress'.")
        category = "in_progress"

    p = Path(path).expanduser().resolve()
    if not p.exists():
        print(f"[x] Path not found: {p}")
        return

    hash_str = hash_path(p)
    inv = load_inventory(DB_PATH)

    # check duplicates
    for proj in inv["projects"]:
        if proj["hash"] == hash_str:
            print(f"[!] Duplicate detected: {proj['id']} at {proj['path']}")
            return

    project_id = generate_id(hash_str)
    dest_dir = BASE_DIR / category / project_id
    dest_dir.parent.mkdir(parents=True, exist_ok=True)

    if p.is_file():
        dest_dir.mkdir(parents=True, exist_ok=True)
        shutil.move(str(p), dest_dir / p.name)
    else:
        shutil.move(str(p), dest_dir)

    record = {
        "id": project_id,
        "name": p.stem,
        "path": str(dest_dir),
        "category": category,
        "status": "working" if category != "idea" else "idea",
        "hash": hash_str,
        "created_at": datetime.datetime.now().isoformat(),
        "updated_at": datetime.datetime.now().isoformat(),
    }

    inv["projects"].append(record)
    save_inventory(DB_PATH, inv)
    print(f"[+] Project {project_id} classified under {category}")


def start_project():
    ensure_environment()
    name = input("Enter new project name (or leave blank for random idea): ").strip()
    if not name:
        name = random_idea()
        print(f"[+] Random idea: {name}")

    category = input(f"Enter category {CATEGORIES}: ").strip()
    if category not in CATEGORIES:
        category = "idea"

    hash_str = hashlib.sha256(name.encode()).hexdigest()
    project_id = generate_id(hash_str)
    project_path = BASE_DIR / category / project_id
    (project_path / "src").mkdir(parents=True, exist_ok=True)

    with open(project_path / "README.md", "w") as f:
        f.write(f"# {name}\n\nGenerated by Prolog.\n")

    with open(project_path / "notes.md", "w") as f:
        f.write("## Notes\n\n")

    record = {
        "id": project_id,
        "name": name,
        "path": str(project_path),
        "category": category,
        "status": "started",
        "hash": hash_str,
        "created_at": datetime.datetime.now().isoformat(),
        "updated_at": datetime.datetime.now().isoformat(),
    }

    inv = load_inventory(DB_PATH)
    inv["projects"].append(record)
    save_inventory(DB_PATH, inv)

    print(f"[+] New project {project_id} created at {project_path}")
    subprocess.run(["kate", str(project_path)])


def list_projects():
    ensure_environment()
    inv = load_inventory(DB_PATH)
    if not inv["projects"]:
        print("[*] No projects yet.")
        return
    print("📂 Current Projects:")
    for proj in inv["projects"]:
        print(f"- {proj['id']} [{proj['category']}] {proj['name']} ({proj['status']})")


def open_project(project_id):
    ensure_environment()
    inv = load_inventory(DB_PATH)
    for proj in inv["projects"]:
        if proj["id"] == project_id:
            subprocess.run(["kate", proj["path"]])
            return
    print("[x] Project ID not found.")
